/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Observer, Subscription } from "rxjs";
export namespace Components {
    interface HoneyApplyStyle {
    }
    interface HoneyDefineStyle {
        /**
          * Trigger recompute theme style.
         */
        "recomputeTheme": () => Promise<void>;
        /**
          * Get the current theme as string in lowercase of tag name.
         */
        "subscribeThemeChangeListener": (observer: Observer<string>) => Promise<Subscription>;
    }
    interface HoneySelectStyle {
        /**
          * Name des zu setzenden Theme z.B. honey-papercss-style
         */
        "themeName": any;
    }
}
declare global {
    interface HTMLHoneyApplyStyleElement extends Components.HoneyApplyStyle, HTMLStencilElement {
    }
    var HTMLHoneyApplyStyleElement: {
        prototype: HTMLHoneyApplyStyleElement;
        new (): HTMLHoneyApplyStyleElement;
    };
    interface HTMLHoneyDefineStyleElement extends Components.HoneyDefineStyle, HTMLStencilElement {
    }
    var HTMLHoneyDefineStyleElement: {
        prototype: HTMLHoneyDefineStyleElement;
        new (): HTMLHoneyDefineStyleElement;
    };
    interface HTMLHoneySelectStyleElement extends Components.HoneySelectStyle, HTMLStencilElement {
    }
    var HTMLHoneySelectStyleElement: {
        prototype: HTMLHoneySelectStyleElement;
        new (): HTMLHoneySelectStyleElement;
    };
    interface HTMLElementTagNameMap {
        "honey-apply-style": HTMLHoneyApplyStyleElement;
        "honey-define-style": HTMLHoneyDefineStyleElement;
        "honey-select-style": HTMLHoneySelectStyleElement;
    }
}
declare namespace LocalJSX {
    interface HoneyApplyStyle {
    }
    interface HoneyDefineStyle {
    }
    interface HoneySelectStyle {
        /**
          * Name des zu setzenden Theme z.B. honey-papercss-style
         */
        "themeName"?: any;
    }
    interface IntrinsicElements {
        "honey-apply-style": HoneyApplyStyle;
        "honey-define-style": HoneyDefineStyle;
        "honey-select-style": HoneySelectStyle;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "honey-apply-style": LocalJSX.HoneyApplyStyle & JSXBase.HTMLAttributes<HTMLHoneyApplyStyleElement>;
            "honey-define-style": LocalJSX.HoneyDefineStyle & JSXBase.HTMLAttributes<HTMLHoneyDefineStyleElement>;
            "honey-select-style": LocalJSX.HoneySelectStyle & JSXBase.HTMLAttributes<HTMLHoneySelectStyleElement>;
        }
    }
}
