/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface HoneyApplyStyle {
        /**
          * tagName of honey style sheet to apply e.g. 'honey-papercss-style'
         */
        "theme": string;
    }
    interface HoneyDefineStyle {
        /**
          * Get the current theme as string in lowercase of tag name.
         */
        "getTheme": () => Promise<string>;
    }
}
declare global {
    interface HTMLHoneyApplyStyleElement extends Components.HoneyApplyStyle, HTMLStencilElement {
    }
    var HTMLHoneyApplyStyleElement: {
        prototype: HTMLHoneyApplyStyleElement;
        new (): HTMLHoneyApplyStyleElement;
    };
    interface HTMLHoneyDefineStyleElement extends Components.HoneyDefineStyle, HTMLStencilElement {
    }
    var HTMLHoneyDefineStyleElement: {
        prototype: HTMLHoneyDefineStyleElement;
        new (): HTMLHoneyDefineStyleElement;
    };
    interface HTMLElementTagNameMap {
        "honey-apply-style": HTMLHoneyApplyStyleElement;
        "honey-define-style": HTMLHoneyDefineStyleElement;
    }
}
declare namespace LocalJSX {
    interface HoneyApplyStyle {
        /**
          * tagName of honey style sheet to apply e.g. 'honey-papercss-style'
         */
        "theme"?: string;
    }
    interface HoneyDefineStyle {
    }
    interface IntrinsicElements {
        "honey-apply-style": HoneyApplyStyle;
        "honey-define-style": HoneyDefineStyle;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "honey-apply-style": LocalJSX.HoneyApplyStyle & JSXBase.HTMLAttributes<HTMLHoneyApplyStyleElement>;
            "honey-define-style": LocalJSX.HoneyDefineStyle & JSXBase.HTMLAttributes<HTMLHoneyDefineStyleElement>;
        }
    }
}
